version: "3.8"
services:
  flask_app:
      build:
        context: .
        dockerfile: Dockerfile.flask
      ports:
        - "5000:5000"
      volumes:
        - ./instance:/app/instance
      # network_mode: bridge
  ap_scheduler:
      build:
        context: .
        dockerfile: Dockerfile.apscheduler
      env_file:
        - .env.prod
      volumes:
        - ./instance:/app/instance
        - ./reports:/app/reports
      # network_mode: bridge