version: "3.8"
services:
  flask_app:
      build:
        context: .
        dockerfile: Dockerfile.flask
      env_file:
        - .env.prod
      ports:
        - "5000:5000"
      volumes:
        - ./instance:/app/instance
      # network_mode: bridge
  ap_scheduler:
      build:
        context: .
        dockerfile: Dockerfile.apscheduler
      env_file:
        - .env.prod
      volumes:
        - ./instance:/app/instance
        - ./reports:/app/reports
      # network_mode: bridge
  postgres_container:
    image: postgres:15.4
    restart: always
    env_file:
        - .env.db
    ports:
      - '5432:5432'
    volumes: 
      - ./db_data:/var/lib/postgresql/data