from datetime import datetime

accounts = [
    {
        "id": "123456",
        "name": "John Doe",
        "username": "johndoe123",
        "email": "johndoe123@gmail.com",
        "balance": 1000.0,
        "password": "1234",
    },
    {
        "id": "789012",
        "name": "Jane Doe",
        "username": "janedoe678",
        "email": "janedoe678@gmail.com",
        "balance": 2000.0,
        "password": "5678",
    },
]

transactions_sample = [
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 200,
        "priority": "default",
        "txn_status": "Success",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-05-10"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 200,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-05-10"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 100,
        "priority": "high",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-04-10"),
    },
     {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 100,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-04-10"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 100,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },{
        "from_account": "123456",
        "to_account": "789012",
        "amount": 100,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 10000,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 10000,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-04-12"),
    },
    {
        "from_account": "123456",
        "to_account": "789012",
        "amount": 10000,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-05-12"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 250,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-05-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 200,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-04-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 100,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 100,
        "priority": "high",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 250,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 300,
        "priority": "default",
        "txn_status": "Pending",
        "txn_description": None,
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 100,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-03-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 100,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-04-10"),
    },
    {
        "from_account": "789012",
        "to_account": "123456",
        "amount": 100,
        "priority": "default",
        "txn_status": "InsufficientFunds",
        "txn_description": "Insufficient balance in Account",
        "timestamp": datetime.fromisoformat("2024-05-11"),
    },
]
